version: "2"
services:
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx
      - ./nginx/ssl:/etc/ssl
  # user=ejemplo
  # pass=ejemplo
  microservicios:
    build: ./docker_microservicios
    container_name: microservicios
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./src:/usr/src/app
