version: "2"
services:
  elasticsearch:
    image: elasticsearch
    container_name: elasticsearch
    volumes:
      - ${ES_DATA}:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: kibana
    container_name: kibana
    volumes:
      - ${K_CONFIG}:/etc/kibana/
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
